<?php
/**
 * Elite: Dangerous Star Map
 *
 * @link        https://www.edsm.net/
 * @copyright   Copyright (c) 2015-2017 EDSM.
 */
 
namespace   Alias\Station\Engineer\Effect;
use         EDSM\Alias;

class Description extends Alias
{
    /**
     * List of experimental effects descriptions
     */
    static protected $name  = [
          1     => 'Custom angling of plates at critical points along the ship\'s hull make projectile strikes more likely to glance, reducing the impact of kinetic damage at the cost of structural integrity.',
          2     => 'Custom angling of plates at critical points along the ship\'s hull make projectile strikes more likely to glance, reducing the impact of kinetic damage at the cost of reducing structural integrity benefits.',
          3     => 'An experimental upgrade that automatically reloads the weapon, even when firing.',
          4     => 'Advanced field resonation patterns increase resistance to explosive damage, at the cost of overall shield strength.',
          5     => 'Oversized cells offer increased cell strength at cost of an increased spin up time.',
          6     => 'Additional capacitor arrays allow the power distributor to store more energy at the cost of a slower charging rate.',
          7     => 'A modification that causes weapon strikes to temporarily enhance the regeneration rate of a wingman\'s shield, at the cost of increased heat generation.',
          8     => 'Experimental rounds that temporarily weaken hull hardness and increase all damage taken, at the cost of reduced ammo capacity.',
          9     => 'Experimental shells that temporarily reduce a target\'s sensor acuity upon impact.',
         10     => 'Toughened FSD power conduits and a reinforced charging field increase the amount of fuel injected when charging, allowing larger jumps at the cost of increased power draw.',
         11     => 'Increased depth of plating increases the ship\'s overall structural integrity, at the cost of resistance against all types of damage.',
         12     => 'Increased depth of plating increases the ship\'s overall structural integrity, at the cost of resistance against all types of damage.',
         13     => 'Experimental upgrade that causes successful strikes to temporarily confuse all gimbal and turret hardpoints on the target, at the cost of direct damage potential.',
         14     => 'Additional, hardened supports and bracing further improve module survivability.',
         15     => 'Additional, hardened supports and bracing further improve module survivability.',
         16     => 'Additional, hardened supports and bracing further improve module survivability.',
         17     => 'Additional, hardened supports and bracing further improve module survivability.',
         18     => 'Additional, hardened supports and bracing further improve module survivability.',
         19     => 'Additional, hardened supports and bracing further improve module survivability.',
         20     => 'Additional, hardened supports and bracing further improve module survivability.',
         21     => 'Additional, hardened supports and bracing further improve module survivability.',
         22     => 'Removal of safety protocols in controller software to increase drive thrust output at the cost of additional heat generation.',
         23     => 'Experimental munitions that disrupt engine exhaust flow on the target, temporarily preventing ENG power distribution from increasing thrust.',
         24     => 'Enhanced fuel and thrust balancing across the drives to improve mass curve efficiency.',
         25     => 'Experimental upgrade that causes strikes to envelope the target in energetic particles, significantly amplifying its signature, at the cost of increasing heat generation for the attacker.',
         26     => 'High speed charging units increase shield regeneration rate when active and reforming, at the cost of slightly weaker resistance versus all forms of damage.',
         27     => 'Rail slug energy charging mechanism, designed to interfere with shield cell operation. Strikes to a target deploying a shield cell will damage the shield cell bank and reduce shield restoration, at the cost of reduced damage from smaller rounds.',
         28     => 'Rail slug energy charging mechanism, designed to interfere with shield cell operation. Strikes to a target deploying a shield cell will damage the shield cell bank and reduce shield restoration, at the cost of reduced damage from smaller rounds.',
         29     => 'Advanced software and internal sensors regulate energy flow more efficiently, reducing module power draw.',
         30     => 'Advanced software and internal sensors regulate energy flow more efficiently, reducing module power draw.',
         31     => 'Advanced software and internal sensors regulate energy flow more efficiently, reducing module power draw.',
         32     => 'Advanced software and internal sensors regulate energy flow more efficiently, reducing module power draw.',
         33     => 'Enlarged projection nodes increase resistance to kinetic damage, at the cost of overall shield strength.',
         34     => 'Enlarged projection nodes increase resistance to kinetic damage, at the cost of overall shield strength.',
         35     => 'A modification to allow firing of low explosive shells, designed to generate a propelling blast. Strikes to a target are capable of forcing ships off course, at the cost of shot accuracy.',
         36     => 'Experimental munitions that cause the frame shift drive on the impacted ship to reboot, at the cost of reduced damage.',
         37     => 'Additional capacitors and projection nodes increase maximum shield strength, at the cost of increased power draw and SYS drain.',
         38     => 'Modified munitions that convert a portion of damage to explosive, capable of hitting multiple internal modules if the attack breaches the hull, at the cost of a reduced fire rate.',
         39     => 'Modified ammo system capable of delivering superheated rounds, increasing damage and converting a large portion to thermal.',
         40     => 'Experimental upgrade that increases damage and converts half of it to kinetic, at the cost of introducing aiming jitter.',
         41     => 'Experimental munitions capable of disrupting a target\'s drives, causing them to reboot.',
         42     => 'Layers of advanced inert lining material within the ship\'s plating absorb and redistribute the force from explosive attacks, reducing damage of this type at the cost of overall structural integrity.',
         43     => 'Layers of advanced inert lining material within the ship\'s plating absorb and redistribute the force from explosive attacks, reducing damage of this type at the cost of reducing structural integrity benefits.',
         44     => 'Lightweight component swaps and smaller charging units reduce power draw and SYS drain, at the cost of overall shield effectiveness.',
         45     => 'Experimental warheads incorporating frame shift technology. Successful detonation significantly inhibits charging for supercruise.',
         46     => 'Complex software upgrade and internal sensor suite able to optimise frame shift operation by analysing and accounting for ship loadout. Increases optimised mass at the cost of module health.',
         47     => 'Oversized, reinforced components increase power output at the cost of increased mass.',
         48     => 'Additional servomechanisms and controller software allow the weapon to safely fire at an increased rate, at the cost of increased power draw.',
         49     => 'Reinforced shield weave structures increase resistance versus all types of damage, at the cost of increased power draw and SYS drain.',
         50     => 'Experimental munitions that convert a portion of explosive damage to thermal.',
         51     => 'Scaled up components and reinforced munitions housing allows the weapon to pack more of a punch, increasing damage at the cost of increased power draw.',
         52     => 'Experimental munitions capable of penetrating hull to damage internal modules.',
         53     => 'Deep cut munitions are guaranteed to penetrate upon impact with hull and are capable of damaging multiple internal modules.',
         54     => 'Modulating burst fire system designed to defeat shielding. A small amount of damage is able to bleed through shields and attack the target\'s hull directly, at the cost of minor damage reduction.',
         55     => 'Experimental upgrade allowing plasma slug ammo to be generated directly from ship fuel, at the cost of reduced damage.',
         56     => 'Experimental upgrade allowing plasma slug ammo to be generated directly from ship fuel, at the cost of reduced damage.',
         57     => 'Experimental munitions that apply significant heat to all targets caught in the blast radius. In addition, targets\' sensors are temporarily disrupted, at the cost of ammo capacity.',
         58     => 'Upgrated resonating coils maximise the amount of time the shield cell can remain active before depleting, at the cost of overall strength of the cell charge.',
         59     => 'Surface coating of advanced formulas designed to reflect and dissipate thermal energy, at the cost of structural integrity.',
         60     => 'Surface coating of advanced formulas designed to reflect and dissipate thermal energy, at the cost of reducing structural integrity benefits.',
         61     => 'Friend or Foe Beam modulation upgrade. When the beam strikes a wingman\'s shields its energy is regulated, regenerating the shield instead of damaging it.',
         62     => 'Experimental munitions that overload shields on impact, directly damaging the shield generator.',
         63     => 'Experimental upgrade that allows hull strikes to potentially trigger random malfunctions on the target.',
         64     => 'Modified firing and targeting mechanism, decreasing reload times and increasing effectiveness against munitions.',
         65     => 'Experimental munitions that cause all frame shift drives caught in the blast radius to reboot, at the cost of reduced damage.',
         66     => 'Friend or foe targeting upgrade that causes rounds to self-destruct before damaging ships that are not currently targeted.',
         67     => 'Key components replaced with versions crafted from lightweight materials and all extraneous parts removed entirely to reduce mass.',
         68     => 'Key components replaced with versions crafted from lightweight materials and all extraneous parts removed entirely to reduce mass.',
         68     => 'Key components replaced with versions crafted from lightweight materials and all extraneous parts removed entirely to reduce mass.',
         69     => 'Key components replaced with versions crafted from lightweight materials and all extraneous parts removed entirely to reduce mass.',
         70     => 'Key components replaced with versions crafted from lightweight materials and all extraneous parts removed entirely to reduce mass.',
         71     => 'Key components replaced with versions crafted from lightweight materials and all extraneous parts removed entirely to reduce mass.',
         72     => 'Key components replaced with versions crafted from lightweight materials and all extraneous parts removed entirely to reduce mass.',
         73     => 'Additional, advanced capacitors increases overall shield strength at the cost of damage resistance.',
         74     => 'Advanced, oversized energy conduits increase the power distributor\'s charge rate at the cost of reduced maximum charge potential.',
         75     => 'Experimental munitions that are capable of penetrating and damaging all modules along its trajectory, at the cost of increased reload times.',
         76     => 'Experimental munitions that are capable of penetrating and damaging all modules along its trajectory, at the cost of increased reload times.',
         77     => 'Experimental upgrade that breaks target lock on successful strikes.',
         78     => 'Experimental munitions that interact with shields upon detonation, generating significant heat on the target.',
         79     => 'Experimental upgrade that increases damage output based on heat level of the firing ship.',
         80     => 'Articulated focus array designed to spread heat effectively. Strikes to shields and hull impart additional heat into the target.',
         81     => 'Additional thermal conduits and radiator solutions integrated across the module help balance thermal load increase cooling potential at the cost of slight mass increase.',
         82     => 'Additional thermal conduits and radiator solutions integrated across the module help balance thermal load increase cooling potential.',
         83     => 'Additional thermal conduits and radiator solutions integrated across the module help balance thermal load increase cooling potential.',
         84     => 'Experimental upgrade that increases heat dissipation when successfully striking a target, at the cost of increased heat generation when missing.',
         85     => 'Improved feedback protection and reinforced projection nodes increase resistance to thermal damage, at the cost of overall shield strength.',
         86     => 'Improved feedback protection and reinforced projection nodes increase resistance to thermal damage, at the cost of overall shield strength.',
    ];
}