<?php
/**
 * Elite: Dangerous Star Map
 *
 * @link        https://www.edsm.net/
 * @copyright   Copyright (c) 2015-2017 EDSM.
 */
 
namespace   Alias\Station\Engineer\Effect;
use         EDSM\Alias;

class Type extends Alias
{
    /**
     * List of experimental effects names
     */
    static protected $name  = [
          1     => 'Angled Plating for Armours',
          2     => 'Angled Plating for Hull/Module Reinforcements',
          3     => 'Auto Loader for Cannons, Multi-cannons',
          4     => 'Blast Block for Shield Boosters',
          5     => 'Boss Cells for Shield Cell Banks',
          6     => 'Cluster Capacitors for Power Distributors',
          7     => 'Concordant Sequence for Pulse Lasers, Burst Lasers, Beam Lasers',
          8     => 'Corrosive Shell for Multi-cannons, Fragment Cannons',
          9     => 'Dazzle Shell for Plasma Accelerators, Fragment Cannons',
         10     => 'Deep Charge for Frame Shift Drives',
         11     => 'Deep Plating for Armours',
         12     => 'Deep Plating for Hull/Module Reinforcements',
         13     => 'Dispersal Field for Plasma Accelerators, Cannons',
         14     => 'Double Braced for Shield Generators',
         15     => 'Double Braced for Thrusters',
         16     => 'Double Braced for Frame Shift Drives',
         17     => 'Double Braced for Power Plants',
         18     => 'Double Braced for Power Distributors',
         19     => 'Double Braced for Shield Cell Banks',
         20     => 'Double Braced for Beam Lasers, Burst Lasers, Pulse Lasers, Multi-cannons, Plasma Accelerators, Fragment Cannons, Cannons, Rail Guns, Mine Launchers, Torpedo Pylons',
         21     => 'Double Braced for Shield Boosters',
         22     => 'Drag Drives for Thrusters',
         23     => 'Drag Munitions for Fragment Cannons, Seeker Missiles',
         24     => 'Drive Distributors for Thrusters',
         25     => 'Emissive Munitions for Pulse Lasers, Multi-cannons, Seeker Missiles, Dumb Missiles, Mine Launchers',
         26     => 'Fast Charge for Shield Generators',
         27     => 'Feedback Cascade for Rail Guns',
         28     => 'Feedback Cascade',
         29     => 'Flow Control for Power Distributors',
         30     => 'Flow Control for Shield Cell Banks',
         31     => 'Flow Control for Beam Lasers, Burst Lasers, Pulse Lasers, Multi-cannons, Plasma Accelerators, Fragment Cannons, Cannons, Rail Guns, Mine Launchers, Torpedo Pylons',
         32     => 'Flow Control for Shield Boosters',
         33     => 'Force Block for Shield Generators',
         34     => 'Force Block for Shield Boosters',
         35     => 'Force Shell for Cannons',
         36     => 'FSD Interrupt for Dumb Missiles',
         37     => 'Hi-Cap for Shield Generators',
         38     => 'High Yield Shell for Cannons',
         39     => 'Incendiary Rounds for Multi-cannons, Fragment Cannons',
         40     => 'Inertial Impact for Burst Lasers',
         41     => 'Ion Disruption for Mine Launchers',
         42     => 'Layered Plating for Armours',
         43     => 'Layered Plating for Hull/Module Reinforcements',
         44     => 'Lo-draw for Shield Generators',
         45     => 'Mass Lock Munition for Torpedo Pylons',
         46     => 'Mass Manager for Frame Shift Drives',
         47     => 'Monstered for Power Plants',
         48     => 'Multi-servos for Pulse Lasers, Burst Lasers, Cannons, Multi-cannons, Plasma Accelerators, Rail Guns, Fragment Cannons',
         49     => 'Multi-weave for Shield Generators',
         50     => 'Overload Munitions for Seeker Missiles, Dumb Missiles, Mine Launchers',
         51     => 'Oversized for Beam Lasers, Burst Lasers, Pulse Lasers, Multi-cannons, Plasma Accelerators, Fragment Cannons, Cannons, Rail Guns, Mine Launchers, Torpedo Pylons',
         52     => 'Penetrator Munitions for Dumb Missiles',
         53     => 'Penetrator Payload for Torpedo Pylons',
         54     => 'Phasing Sequence for Pulse Lasers, Burst Lasers, Plasma Accelerators',
         55     => 'Plasma Slug for Plasma Accelerators',
         56     => 'Plasma Slug for Rail Guns',
         57     => 'Radiant Canister for Mine Launchers',
         58     => 'Recycling Cell for Shield Cell Banks',
         59     => 'Reflective Plating for Armours',
         60     => 'Reflective Plating for Hull/Module Reinforcements',
         61     => 'Regeneration Sequence for Beam Lasers',
         62     => 'Reverberating Cascade for Torpedo Pylons, Mine Launchers',
         63     => 'Scramble Spectrum for Pulse Lasers, Burst Lasers',
         64     => 'Screening Shell for Fragment Cannons',
         65     => 'Shift-lock Canister for Mine Launchers',
         66     => 'Smart Rounds for Cannons, Multi-cannons',
         67     => 'Stripped Down for Shield Generators',
         68     => 'Stripped Down for Thrusters',
         68     => 'Stripped Down for Frame Shift Drives',
         69     => 'Stripped Down for Power Plants',
         70     => 'Stripped Down for Power Distributors',
         71     => 'Stripped Down for Shield Cell Banks',
         72     => 'Stripped Down for Beam Lasers, Burst Lasers, Pulse Lasers, Multi-cannons, Plasma Accelerators, Fragment Cannons, Cannons, Rail Guns, Mine Launchers, Torpedo Pylons',
         73     => 'Super Capacitors for Shield Boosters',
         74     => 'Super Conduits for Power Distributors',
         75     => 'Super Penetrator for Rail Guns',
         76     => 'Super Penetrator',
         77     => 'Target Lock Breaker for Plasma Accelerators',
         78     => 'Thermal Cascade for Cannons, Seeker Missiles, Dumb Missiles',
         79     => 'Thermal Conduit for Beam Lasers, Plasma Accelerators',
         80     => 'Thermal Shock for Pulse Lasers, Burst Lasers, Beam Lasers, Multi-cannons',
         81     => 'Thermal Spread for Thrusters',
         82     => 'Thermal Spread for Frame Shift Drives',
         83     => 'Thermal Spread for Power Plants',
         84     => 'Thermal Vent for Beam Lasers',
         85     => 'Thermo Block for Shield Generators',
         86     => 'Thermo Block for Shield Boosters',
    ];
}