<?php
/**
 * Elite Dangerous Star Map
 * @link https://www.edsm.net/
 */
namespace Alias\Commander\MicroResource;

use EDSM\Alias;

class Type extends Alias
{
    /**
     * List of names used in game
     */
    static protected $name = [
        // Items
        1001 => 'Agricultural Process Sample',
        1002 => 'Biochemical Agent',
        1003 => 'Biological Sample',
        1004 => 'Building Schematic',
        1005 => 'Californium',
        1006 => 'Cast Fossil',
        1007 => 'Chemical Process Sample',
        1008 => 'Chemical Sample',
        1009 => 'Compact Library',
        1010 => 'Compression-Liquefied Gas',
        1011 => 'Deep Mantle Sample',
        1012 => 'Degraded Power Regulator',
        1013 => 'Genetic Repair Meds',
        1014 => 'G-Meds',
        1015 => 'Health Monitor',
        1016 => 'Hush',
        1017 => 'Inertia Canister',
        1018 => 'Infinity',
        1019 => 'Inorganic Contaminant',
        1020 => 'Insight',
        1021 => 'Insight Data Bank',
        1022 => 'Insight Entertainment Suite',
        1023 => 'Ionised Gas',
        1024 => 'Lazarus',
        1025 => 'Microbial Inhibitor',
        1026 => 'Mutagenic Catalyst',
        1027 => 'Nutritional Concentrate',
        1028 => 'Personal Computer',
        1029 => 'Personal Documents',
        1030 => 'Petrified Fossil',
        1031 => 'Power Regulator',
        1032 => 'Push',
        1033 => 'Pyrolytic Catalyst',
        1034 => 'Refinement Process Sample',
        1035 => 'Ship Schematic',
        1036 => 'Suit Schematic',
        1037 => 'Surveillance Equipment',
        1038 => 'Synthetic Genome',
        1039 => 'Synthetic Pathogen',
        1040 => 'True Form Fossil',
        1041 => 'Universal Translator',
        1042 => 'Vehicle Schematic',
        1043 => 'Weapon Schematic',
        1044 => 'Spire Refinery Compound',
        1045 => 'Spire Refinery Compound',
        1046 => 'Contaminated Spire Refinery Compound',
        
        // Consumbales
        1501 => 'Energy Cell',
        1502 => 'Medkit',
        1503 => 'E-Breach',
        1504 => 'Frag Grenade',
        1505 => 'Shield Disruptor',
        1506 => 'Shield Projector',
        
        // Data
        2001 => 'Accident Logs',
        2002 => 'Air Quality Reports',
        2003 => 'Atmospheric Data',
        2004 => 'Audio Logs',
        2005 => 'AX Combat Logs',
        2006 => 'Ballistics Data',
        2007 => 'Biological Weapon Data',
        2008 => 'Biometric Data',
        2009 => 'Blacklist Data',
        2010 => 'Blood Test Results',
        2011 => 'Campaign Plans',
        2012 => 'Cat Media',
        2013 => 'Census Data',
        2014 => 'Chemical Experiment Data',
        2015 => 'Chemical Formulae',
        2016 => 'Chemical Inventory',
        2017 => 'Chemical Patents',
        2018 => 'Chemical Weapon Data',
        2019 => 'Classic Entertainment',
        2020 => 'Cocktail Recipes',
        2021 => 'Combat Training Material',
        2022 => 'Combatant Performance',
        2023 => 'Conflict History',
        2024 => 'Criminal Records',
        2025 => 'Crop Yield Analysis',
        2026 => 'Culinary Recipes',
        2027 => 'Digital Designs',
        2028 => 'Duty Rota',
        2029 => 'Employee Directory',
        2030 => 'Employee Expenses',
        2031 => 'Employee Genetic Data',
        2032 => 'Employment History',
        2033 => 'Enhanced Interrogation Recordings',
        2034 => 'Espionage Material',
        2035 => 'Evacuation Protocols',
        2036 => 'Exploration Journals',
        2037 => 'Extraction Yield Data',
        2038 => 'Faction Associates',
        2039 => 'Faction Donator List',
        2040 => 'Faction News',
        2041 => 'Financial Projections',
        2042 => 'Fleet Registry',
        2043 => 'Gene Sequencing Data',
        2044 => 'Genetic Research',
        2045 => 'Geological Data',
        2046 => 'Hydroponic Data',
        2047 => 'Incident Logs',
        2048 => 'Influence Projections',
        2049 => 'Internal Correspondence',
        2050 => 'Interrogation Recordings',
        2051 => 'Interview Recordings',
        2052 => 'Job Applications',
        2053 => 'Kompromat',
        2054 => 'Literary Fiction',
        2055 => 'Maintenance Logs',
        2056 => 'Manufacturing Instructions',
        2057 => 'Medical Records',
        2058 => 'Clinical Trial Records',
        2059 => 'Meeting Minutes',
        2060 => 'Mineral Survey',
        2061 => 'Mining Analytics',
        2062 => 'Multimedia Entertainment',
        2063 => 'Network Access History',
        2064 => 'Network Security Protocols',
        2065 => 'Next of Kin Records',
        2066 => 'NOC Data',
        2067 => 'Operational Manual',
        2068 => 'Opinion Polls',
        2069 => 'Patient History',
        2070 => 'Patrol Routes',
        2071 => 'Payroll Information',
        2072 => 'Personal Logs',
        2073 => 'Pharmaceutical Patents',
        2074 => 'Photo Albums',
        2075 => 'Plant Growth Charts',
        2076 => 'Political Affiliations',
        2077 => 'Prisoner Logs',
        2078 => 'Production Reports',
        2079 => 'Production Schedule',
        2080 => 'Propaganda',
        2081 => 'Purchase Records',
        2082 => 'Purchase Requests',
        2083 => 'Radioactivity Data',
        2084 => 'Reactor Output Review',
        2085 => 'Recycling Logs',
        2086 => 'Residential Directory',
        2087 => 'Risk Assessments',
        2088 => 'Sales Records',
        2089 => 'Security Expenses',
        2090 => 'Seed Geneaology',
        2091 => 'Settlement Assault Plans',
        2092 => 'Settlement Defence Plans',
        2093 => 'Shareholder Information',
        2094 => 'Slush Fund Logs',
        2095 => 'Smear Campaign Plans',
        2096 => 'Spectral Analysis Data',
        2097 => 'Spyware',
        2098 => 'Stellar Activity Logs',
        2099 => 'Surveillance Logs',
        2100 => 'Tactical Plans',
        2101 => 'Tax Records',
        2102 => 'Topographical Surveys',
        2103 => 'Travel Permits',
        2104 => 'Troop Deployment Records',
        2105 => 'Union Membership',
        2106 => 'Vaccination Records',
        2107 => 'Vaccine Research',
        2108 => 'VIP Security Detail',
        2109 => 'Virology Data',
        2110 => 'Virus',
        2111 => 'Visitor Register',
        2112 => 'Weapon Inventory',
        2113 => 'Weapon Test Data',
        2114 => 'Xeno-Defence Protocols',
        
        // Assets - Chemicals
        3001 => 'Aerogel',
        3002 => 'Chemical Catalyst',
        3003 => 'Chemical Superbase',
        3004 => 'Epinephrine',
        3005 => 'Epoxy Adhesive',
        3006 => 'Graphene',
        3007 => 'Oxygenic Bacteria',
        3008 => 'pH Neutraliser',
        3009 => 'RDX',
        3010 => 'Viscoelastic Polymer',
        
        // Assets - Circuits
        4001 => 'Circuit Board',
        4002 => 'Circuit Switch',
        4003 => 'Electrical Fuse',
        4004 => 'Electrical Wiring',
        4005 => 'Electromagnet',
        4006 => 'Ion Battery',
        4007 => 'Metal Coil',
        4008 => 'Micro Supercapacitor',
        4009 => 'Micro Transformer',
        4010 => 'Microelectrode',
        4011 => 'Motor',
        4012 => 'Optical Fibre',
        
        // Assets - Tech
        5001 => 'Carbon Fibre Plating',
        5002 => 'Encrypted Memory Chip',
        5003 => 'Memory Chip',
        5004 => 'Micro Hydraulics',
        5005 => 'Micro Thrusters',
        5006 => 'Optical Lens',
        5007 => 'Scrambler',
        5008 => 'Titanium Plating',
        5009 => 'Transmitter',
        5010 => 'Tungsten Carbide',
        5011 => 'Weapon Component',
        
        // Assets - Powerplay
        9901 => 'Power Injection Malware',
        9902 => 'Power Association Data',
        9903 => 'Power Classified Data',
        9904 => 'Power Industrial Data',
        9905 => 'Power Megaship Data',
        9906 => 'Power Political Data',
        9907 => 'Power Research Data',
        9908 => 'Power Tracker Malware',
        
        9951 => 'Research Notes',
        9952 => 'Medical Sample',
        9953 => 'Industrial Component',
        9954 => 'Agricultural Sample',
        9955 => 'Energy Regulator',
        9956 => 'Industrial Machinery',
        9957 => 'Inventory Record',
        9958 => 'Data Storage Device',
        9959 => 'Extraction Sample',
        9960 => 'Security Logs',
        9961 => 'Electronics Package',
        9962 => 'Personal Protective Equipment',
        9963 => 'Experiment Prototype',
        9964 => 'Computer Parts',
        9965 => 'Military Schematic',
    ];

    /**
     * List of aliases received from Frontier
     *
     * Every aliases are sanitized before matching
     *     => trim
     *     => strtolower
     */
    static protected $alias = [
        // Items
        'agriculturalprocesssample'       => 1001,
        'biochemicalagent'                => 1002,
        'geneticsample'                   => 1003,
        'buildingschematic'               => 1004,
        'californium'                     => 1005,
        'castfossil'                      => 1006,
        'chemicalprocesssample'           => 1007,
        'chemicalsample'                  => 1008,
        'compactlibrary'                  => 1009,
        'compressionliquefiedgas'         => 1010,
        'deepmantlesample'                => 1011,
        'degradedpowerregulator'          => 1012,
        'geneticrepairmeds'               => 1013,
        'gmeds'                           => 1014,
        'healthmonitor'                   => 1015,
        'hush'                            => 1016,
        'inertiacanister'                 => 1017,
        'infinity'                        => 1018,
        'inorganiccontaminant'            => 1019,
        'insight'                         => 1020,
        'insightdatabank'                 => 1021,
        'insightentertainmentsuite'       => 1022,
        'ionisedgas'                      => 1023,
        'lazarus'                         => 1024,
        'microbialinhibitor'              => 1025,
        'mutageniccatalyst'               => 1026,
        'nutritionalconcentrate'          => 1027,
        'personalcomputer'                => 1028,
        'personaldocuments'               => 1029,
        'petrifiedfossil'                 => 1030,
        'largecapacitypowerregulator'     => 1031,
        'push'                            => 1032,
        'pyrolyticcatalyst'               => 1033,
        'refinementprocesssample'         => 1034,
        'shipschematic'                   => 1035,
        'suitschematic'                   => 1036,
        'surveillanceequipment'           => 1037,
        'syntheticgenome'                 => 1038,
        'syntheticpathogen'               => 1039,
        'trueformfossil'                  => 1040,
        'universaltranslator'             => 1041,
        'vehicleschematic'                => 1042,
        'weaponschematic'                 => 1043,
        'biomechanicalcomponent'          => 1044,
        'biomechanicalcomponent'          => 1045,
        'sabotagedcomponent'              => 1046,
        
        // Consumables
        'energycell'                      => 1501,
        'healthpack'                      => 1502,
        'bypass'                          => 1503,
        'amm_grenade_frag'                => 1504,
        'amm_grenade_emp'                 => 1505,
        'amm_grenade_shield'              => 1506,
        
        // Data
        'accidentlogs'                    => 2001,
        'airqualityreports'               => 2002,
        'atmosphericdata'                 => 2003,
        'audiologs'                       => 2004,
        'axcombatlogs'                    => 2005,
        'ballisticsdata'                  => 2006,
        'biologicalweapondata'            => 2007,
        'biometricdata'                   => 2008,
        'blacklistdata'                   => 2009,
        'bloodtestresults'                => 2010,
        'campaignplans'                   => 2011,
        'catmedia'                        => 2012,
        'censusdata'                      => 2013,
        'chemicalexperimentdata'          => 2014,
        'chemicalformulae'                => 2015,
        'chemicalinventory'               => 2016,
        'chemicalpatents'                 => 2017,
        'chemicalweapondata'              => 2018,
        'classicentertainment'            => 2019,
        'cocktailrecipes'                 => 2020,
        'combattrainingmaterial'          => 2021,
        'combatantperformance'            => 2022,
        'conflicthistory'                 => 2023,
        'criminalrecords'                 => 2024,
        'cropyieldanalysis'               => 2025,
        'culinaryrecipes'                 => 2026,
        'digitaldesigns'                  => 2027,
        'dutyrota'                        => 2028,
        'employeedirectory'               => 2029,
        'employeeexpenses'                => 2030,
        'employeegeneticdata'             => 2031,
        'employmenthistory'               => 2032,
        'enhancedinterrogationrecordings' => 2033,
        'espionagematerial'               => 2034,
        'evacuationprotocols'             => 2035,
        'explorationjournals'             => 2036,
        'extractionyielddata'             => 2037,
        'factionassociates'               => 2038,
        'factiondonatorlist'              => 2039,
        'factionnews'                     => 2040,
        'financialprojections'            => 2041,
        'fleetregistry'                   => 2042,
        'genesequencingdata'              => 2043,
        'geneticresearch'                 => 2044,
        'geologicaldata'                  => 2045,
        'hydroponicdata'                  => 2046,
        'incidentlogs'                    => 2047,
        'influenceprojections'            => 2048,
        'internalcorrespondence'          => 2049,
        'interrogationrecordings'         => 2050,
        'interviewrecordings'             => 2051,
        'jobapplications'                 => 2052,
        'kompromat'                       => 2053,
        'literaryfiction'                 => 2054,
        'maintenancelogs'                 => 2055,
        'manufacturinginstructions'       => 2056,
        'medicalrecords'                  => 2057,
        'medicaltrialrecords'             => 2058,
        'meetingminutes'                  => 2059,
        'mineralsurvey'                   => 2060,
        'mininganalytics'                 => 2061,
        'multimediaentertainment'         => 2062,
        'networkaccesshistory'            => 2063,
        'networksecurityprotocols'        => 2064,
        'nextofkinrecords'                => 2065,
        'nocdata'                         => 2066,
        'operationalmanual'               => 2067,
        'opinionpolls'                    => 2068,
        'patienthistory'                  => 2069,
        'patrolroutes'                    => 2070,
        'payrollinformation'              => 2071,
        'personallogs'                    => 2072,
        'pharmaceuticalpatents'           => 2073,
        'photoalbums'                     => 2074,
        'plantgrowthcharts'               => 2075,
        'politicalaffiliations'           => 2076,
        'prisonerlogs'                    => 2077,
        'productionreports'               => 2078,
        'productionschedule'              => 2079,
        'propaganda'                      => 2080,
        'purchaserecords'                 => 2081,
        'purchaserequests'                => 2082,
        'radioactivitydata'               => 2083,
        'reactoroutputreview'             => 2084,
        'recyclinglogs'                   => 2085,
        'residentialdirectory'            => 2086,
        'riskassessments'                 => 2087,
        'salesrecords'                    => 2088,
        'securityexpenses'                => 2089,
        'seedgeneaology'                  => 2090,
        'settlementassaultplans'          => 2091,
        'settlementdefenceplans'          => 2092,
        'shareholderinformation'          => 2093,
        'slushfundlogs'                   => 2094,
        'smearcampaignplans'              => 2095,
        'spectralanalysisdata'            => 2096,
        'spyware'                         => 2097,
        'stellaractivitylogs'             => 2098,
        'surveilleancelogs'               => 2099,
        'tacticalplans'                   => 2100,
        'taxrecords'                      => 2101,
        'topographicalsurveys'            => 2102,
        'travelpermits'                   => 2103,
        'troopdeploymentrecords'          => 2104,
        'unionmembership'                 => 2105,
        'vaccinationrecords'              => 2106,
        'vaccineresearch'                 => 2107,
        'vipsecuritydetail'               => 2108,
        'virologydata'                    => 2109,
        'virus'                           => 2110,
        'visitorregister'                 => 2111,
        'weaponinventory'                 => 2112,
        'weapontestdata'                  => 2113,
        'xenodefenceprotocols'            => 2114,
        
        // Assets - Chemicals
        'aerogel'                         => 3001,
        'chemicalcatalyst'                => 3002,
        'chemicalsuperbase'               => 3003,
        'epinephrine'                     => 3004,
        'epoxyadhesive'                   => 3005,
        'graphene'                        => 3006,
        'oxygenicbacteria'                => 3007,
        'phneutraliser'                   => 3008,
        'rdx'                             => 3009,
        'viscoelasticpolymer'             => 3010,
        
        // Assets - Circuits
        'circuitboard'                    => 4001,
        'circuitswitch'                   => 4002,
        'electricalfuse'                  => 4003,
        'electricalwiring'                => 4004,
        'electromagnet'                   => 4005,
        'ionbattery'                      => 4006,
        'metalcoil'                       => 4007,
        'microsupercapacitor'             => 4008,
        'microtransformer'                => 4009,
        'microelectrode'                  => 4010,
        'motor'                           => 4011,
        'opticalfibre'                    => 4012,
        
        // Assets - Tech
        'carbonfibreplating'              => 5001,
        'encryptedmemorychip'             => 5002,
        'memorychip'                      => 5003,
        'microhydraulics'                 => 5004,
        'microthrusters'                  => 5005,
        'opticallens'                     => 5006,
        'scrambler'                       => 5007,
        'titaniumplating'                 => 5008,
        'transmitter'                     => 5009,
        'tungstencarbide'                 => 5010,
        'weaponcomponent'                 => 5011,
        
        // Assets - Powerplay
        'powerpreparationspyware'           => 9901,
        'poweremployeedata'                 => 9902,
        'powerclassifieddata'               => 9903,
        'powerfinancialrecords'             => 9904,
        //''  => 9905, => 'Power Megaship Data',
        'powerpropagandadata'               => 9906,
        'powerresearchdata'                 => 9907,
        'powerspyware'                      => 9908,
        
        'powerresearch'                     => 9951,
        'powermedical'                      => 9952,
        'powerindustrial'                   => 9953,
        'poweragriculture'                  => 9954,
        'powerpower'                        => 9955,
        'powermiscindust'                   => 9956,
        'powerinventory'                    => 9957,
        'powermisccomputer'                 => 9958,
        'powerextraction'                   => 9959,
        'powersecurity'                     => 9960,
        'powerelectronics'                  => 9961,
        'powerequipment'                    => 9962,
        'powerexperiment'                   => 9963,
        'powercomputer'                     => 9964,
        'powerplaymilitary'                 => 9965,
    ];

}