<?php
/**
 * Elite Dangerous Star Map
 * @link https://www.edsm.net/
 */

namespace   Alias\Codex;
use         EDSM\Alias;

class Type extends Alias
{
    /**
     * List of names used in game
     */
    static protected $name  = [
        11010                       => 'O Type Star',
            11011                       => 'O Type',
            11012                       => 'O Type Giant',
            11013                       => 'O Type Supergiant',
        11020                       => 'B Type Star',
            11021                       => 'B Type',
            11022                       => 'B Type Giant',
            11023                       => 'B Type Supergiant',
        11030                       => 'A Type Star',
            11031                       => 'A Type',
            11032                       => 'A Type Giant',
            11033                       => 'A Type Supergiant',
        11040                       => 'F Type Star',
            11041                       => 'F Type',
            11042                       => 'F Type Giant',
            11043                       => 'F Type Supergiant',
        11050                       => 'G Type Star',
            11051                       => 'G Type',
            11052                       => 'G Type Giant',
            11053                       => 'G Type Supergiant',
        11060                       => 'K Type Star',
            11061                       => 'K Type',
            11062                       => 'K Type Giant',
            11063                       => 'K Type Supergiant',
        11070                       => 'M Type Star',
            11071                       => 'M Type',
            11072                       => 'M Type Giant',
            11073                       => 'M Type Supergiant',
        11080                       => 'L Type Star',
            11081                       => 'L Type',
        11090                       => 'T Type Star',
            11091                       => 'T Type',
        11100                       => 'T Tauri Type Star',
            11101                       => 'T Tauri Type',
        11110                       => 'AEBE Type Star',
            11111                       => 'AEBE Type',
        11120                       => 'Y Type Star',
            11121                       => 'Y Type',
        11130                       => 'C Type Star',
            11131                       => 'C Type',
            11132                       => 'C Type Giant',
            11133                       => 'C Type Supergiant',
            11134                       => 'C Type Hypergiant',
        11140                       => 'CN Type Star',
            11142                       => 'CN Type Giant',
        11150                       => 'CJ Type Star',
            11152                       => 'CJ Type Giant',
        11160                       => 'MS Type Star',
            11162                       => 'MS Type Giant',
        11170                       => 'S Type Star',
            11171                       => 'S Type',
            11172                       => 'S Type Giant',
        11180                       => 'Wolf-Rayet Star',
            11181                       => 'W Type',
            11183                       => 'WC Type',
            11184                       => 'WN Type',
            11185                       => 'WNC Type',
            11186                       => 'WO Type',
        11190                       => 'White Dwarf Star',
            11191                       => 'D Type Star',
            11192                       => 'DA Type Star',
            11194                       => 'DAB Type Star',
            11196                       => 'DAV Type Star',
            11197                       => 'DAZ Type Star',
            11198                       => 'DB Type Star',
            11199                       => 'DBV Type Star',
            11200                       => 'DBZ Type Star',
            11204                       => 'DO Type Star',
            11205                       => 'DOV Type Star',
            11206                       => 'DQ Type Star',
            11207                       => 'DC Type Star',
            11208                       => 'DCV Type Star',
        11221                       => 'Neutron Star',
        11231                       => 'Black Hole',
        11241                       => 'Supermassive Black Hole',



        12010                       => 'Water Giant planet',
            12011                       => 'Standard Gas Giant',
            12012                       => 'Green Gas Giant',
        12030                       => 'Gas giant planet with water-based life',
            12031                       => 'Standard Gas Giant',
            12032                       => 'Green Gas Giant',
        12050                       => 'Gas giant planet with ammonia-based life',
            12051                       => 'Standard Gas Giant',
        12070                       => 'Class I gas giant planet',
            12071                       => 'Standard Gas Giant',
            12072                       => 'Green Gas Giant',
        12090                       => 'Class II gas giant planet',
            12091                       => 'Standard Gas Giant',
            12092                       => 'Green Gas Giant',
        12110                       => 'Class III gas giant planet',
            12111                       => 'Standard Gas Giant',
            12112                       => 'Green Gas Giant',
        12130                       => 'Class IV gas giant planet',
            12131                       => 'Standard Gas Giant',
        12150                       => 'Class V gas giant planet',
            12151                       => 'Standard Gas Giant',
        12170                       => 'Helium Gas Giant planet',
            12171                       => 'Standard Gas Giant',
        12190                       => 'Helium-Rich Gas Giant planet',
            12191                       => 'Standard Gas Giant',



        13011                       => 'Earth-Like Planet',
        13020                       => 'Ammonia Planet',
            13021                       => 'Non Terraformable',
            13022                       => 'Terraformable',
        13030                       => 'Water planet',
            13031                       => 'Non Terraformable',
            13032                       => 'Terraformable',
        13040                       => 'Metal-Rich planet with no atmosphere',
            13041                       => 'Non Terraformable',
            13042                       => 'Terraformable',
        13050                       => 'High Metal Content planet with no atmosphere',
            13051                       => 'Non Terraformable',
            13052                       => 'Terraformable',
        13060                       => 'Rocky planet with no atmosphere',
            13061                       => 'Non Terraformable',
            13062                       => 'Terraformable',
        13070                       => 'Rocky Ice planet with no atmosphere',
            13071                       => 'Non Terraformable',
        13080                       => 'Ice planet with no atmosphere',
            13081                       => 'Non Terraformable',
        13090                       => 'Metal-Rich planet with atmosphere',
            13091                       => 'Non Terraformable',
            13092                       => 'Terraformable',
        13100                       => 'High Metal Content planet with atmosphere',
            13101                       => 'Non Terraformable',
            13102                       => 'Terraformable',
        13110                       => 'Rocky planet with atmosphere',
            13111                       => 'Non Terraformable',
            13112                       => 'Terraformable',
        13120                       => 'Rocky Ice planet with atmosphere',
            13121                       => 'Non Terraformable',
        13130                       => 'Ice planet with atmosphere',
            13131                       => 'Non Terraformable',



        21010                       => 'Fumarole',
            21011                       => 'Sulphur Dioxide Fumarole',
            21012                       => 'Water Fumarole',
            21013                       => 'Silicate Vapour Fumarole',
            21014                       => 'Carbon Dioxide Fumarole',
        21030                       => 'Ice Fumarole',
            21031                       => 'Sulphur Dioxide Ice Fumarole',
            21032                       => 'Water Ice Fumarole',
            21033                       => 'Carbon Dioxide Ice Fumarole',
            21034                       => 'Ammonia Ice Fumarole',
            21035                       => 'Methane Ice Fumarole',
            21036                       => 'Nitrogen Ice Fumarole',
            21037                       => 'Silicate Vapour Ice Fumarole',
        21050                       => 'Geyser',
            21051                       => 'Water Geyser',
        21070                       => 'Ice Geyser',
            21071                       => 'Water Ice Geyser',
            21072                       => 'Carbon Dioxide Ice Geyser',
            21073                       => 'Ammonia Ice Geyser',
            21074                       => 'Methane Ice Geyser',
            21075                       => 'Nitrogen Ice Geyser',
        21090                       => 'Lava Spout',
            21091                       => 'Silicate Magma Lava Spout',
            21092                       => 'Iron Magma Lava Spout',
        21110                       => 'Gas Vent',
            21111                       => 'Sulphur Dioxide Gas Vent',
            21112                       => 'Water Gas Vent',
            21113                       => 'Carbon Dioxide Gas Vent',
            21114                       => 'Silicate Vapour Gas Vent',
        21130                       => 'Lagrange Clouds',
            21131                       => 'Caeruleum Lagrange Cloud',
            21132                       => 'Viride Lagrange Cloud',
            21133                       => 'Luteolum Lagrange Cloud',
            21134                       => 'Roseum Lagrange Cloud',
            21135                       => 'Rubicundum Lagrange Cloud',
            21136                       => 'Croceum Lagrange Cloud',
            21137                       => 'Proto-Lagrange Cloud',
            21139                       => 'Viride Lagrange Storm Cloud',
            21140                       => 'Luteolum Lagrange Storm Cloud',
            21141                       => 'Roseum Lagrange Storm Cloud',
            21142                       => 'Rubicundum Lagrange Storm Cloud',
            21143                       => 'Croceum Lagrange Storm Cloud',
        21150                       => 'P-Type Anomalies',
            21151                       => 'P01-Type Anomaly',
            21152                       => 'P02-Type Anomaly',
            21153                       => 'P03-Type Anomaly',
            21154                       => 'P04-Type Anomaly',
            21155                       => 'P05-Type Anomaly',
            21157                       => 'P07-Type Anomaly',
            21159                       => 'P09-Type Anomaly',
            21161                       => 'P11-Type Anomaly',
            21162                       => 'P12-Type Anomaly',
            21163                       => 'P13-Type Anomaly',
            21164                       => 'P14-Type Anomaly',
            21165                       => 'P15-Type Anomaly',
        21170                       => 'Q-Type Anomalies',
            21171                       => 'Q01-Type Anomaly',
            21172                       => 'Q02-Type Anomaly',
            21174                       => 'Q04-Type Anomaly',
            21176                       => 'Q06-Type Anomaly',
            21178                       => 'Q08-Type Anomaly',
            21179                       => 'Q09-Type Anomaly',
        21190                       => 'L-Type Anomalies',
            21191                       => 'L01-Type Anomaly',
            21194                       => 'L04-Type Anomaly',
            21195                       => 'L05-Type Anomaly',
            21196                       => 'L06-Type Anomaly',
            21199                       => 'L09-Type Anomaly',
        21210                       => 'K-Type Anomalies',
            21211                       => 'K01-Type Anomaly',
            21212                       => 'K02-Type Anomaly',
            21213                       => 'K03-Type Anomaly',
            21214                       => 'K04-Type Anomaly',
            21215                       => 'K05-Type Anomaly',
            21216                       => 'K06-Type Anomaly',
            21217                       => 'K07-Type Anomaly',
            21218                       => 'K08-Type Anomaly',
            21220                       => 'K10-Type Anomaly',
            21222                       => 'K12-Type Anomaly',
            21223                       => 'K13-Type Anomaly',
        21230                       => 'T-Type Anomalies',
            21231                       => 'T01-Type Anomaly',
            21232                       => 'T02-Type Anomaly',
            21234                       => 'T04-Type Anomaly',
        21250                       => 'E-Type Anomalies',
            21252                       => 'E02-Type Anomaly',
            21254                       => 'E04-Type Anomaly',



        22011                       => 'Solid Mineral Spheres',
        22031                       => 'Lattice Mineral Spheres',
        22050                       => 'Thargoid Barnacles',
            22051                       => 'Common Thargoid Barnacle',
            22052                       => 'Large Thargoid Barnacle',
            22053                       => 'Thargoid Barnacle Barbs',
        22070                       => 'Brain Trees',
            22071                       => 'Roseum Brain Tree',
            22072                       => 'Gypseeum Brain Tree',
            22073                       => 'Ostrinum Brain Tree',
            22074                       => 'Viride Brain Tree',
            22075                       => 'Lividum Brain Tree',
            22076                       => 'Aureum Brain Tree',
            22077                       => 'Lindigoticum Brain Tree',
            22078                       => 'Puniceum Brain Tree',
        22091                       => 'Bark Mounds',
        22110                       => 'Anemones',
            22111                       => 'Luteolum Anemone',
            22112                       => 'Croceum Anemone',
            22113                       => 'Puniceum Anemone',
            22114                       => 'Roseum Anemone',
            22115                       => 'Blatteum Bioluminescent Anemone',
            22116                       => 'Rubeum Bioluminescent Anemone',
            22117                       => 'Prasinum Bioluminescent Anemone',
            22118                       => 'Roseum Bioluminescent Anemone',
        22130                       => 'Sinuous Tubers',
            22131                       => 'Roseum Sinuous Tubers',
            22132                       => 'Prasinum Sinuous Tubers',
            22133                       => 'Albidum Sinuous Tubers',
            22134                       => 'Caeruleum Sinuous Tubers',
            22135                       => 'Blatteum Sinuous Tubers',
            22136                       => 'Lindigoticum Sinuous Tubers',
            22137                       => 'Violaceum Sinuous Tubers',
            22138                       => 'Viride Sinuous Tubers',
        22150                       => 'Metallic Crystals',
            22151                       => 'Prasinum Metallic Crystals',
            22152                       => 'Purpureum Metallic Crystals',
            22153                       => 'Rubeum Metallic Crystals',
            22154                       => 'Flavum Metallic Crystals',
        22170                       => 'Collared Pods',
            22171                       => 'Albidum Collared Pod',
            22172                       => 'Lividum Collared Pod',
            22173                       => 'Blatteum Collared Pod',
            22174                       => 'Rubicundum Collared Pod',
        22190                       => 'Gourd Mollusc',
            22191                       => 'Albulum Gourd Mollusc',
            22192                       => 'Caeruleum Gourd Mollusc',
            22193                       => 'Viride Gourd Mollusc',
            22194                       => 'Phoeniceum Gourd Mollusc',
            22195                       => 'Purpureum Gourd Mollusc',
            22196                       => 'Rufum Gourd Mollusc',
            22197                       => 'Croceum Gourd Mollusc',
        22210                       => 'Ice Crystals',
            22211                       => 'Lindigoticum Ice Crystals',
            22212                       => 'Prasinum Ice Crystals',
            22213                       => 'Roseum Ice Crystals',
            22214                       => 'Purpureum Ice Crystals',
            22215                       => 'Rubeum Ice Crystals',
            22216                       => 'Albidium Ice Crystals',
            22217                       => 'Flavum Ice Crystals',
        22230                       => 'Silicate Crystals',
            22231                       => 'Lindigoticum Silicate Crystals',
            22232                       => 'Prasinum Silicate Crystals',
            22233                       => 'Purpureum Silicate Crystals',
            22234                       => 'Albidium Silicate Crystals',
            22235                       => 'Flavum Silicate Crystals',
            22236                       => 'Rubeum Silicate Crystals',
            22237                       => 'Roseum Silicate Crystals',
        22251                       => 'Crystalline Shards',
        22270                       => 'Peduncle Pods',
            22271                       => 'Candidum peduncle Pod',
            22272                       => 'Caeruleum peduncle Pod',
            22273                       => 'Gypseeum peduncle Pod',
            22274                       => 'Purpureum peduncle Pod',
            22275                       => 'Rufum peduncle Pod',
        22290                       => 'Peduncle Trees',
            22291                       => 'Albidum Peduncle Tree',
            22292                       => 'Caeruleum Peduncle Tree',
            22293                       => 'Viride Peduncle Tree',
            22294                       => 'Ostrinum Peduncle Tree',
            22295                       => 'Rubellum Peduncle Tree',
        22311                       => 'Amphora Plants',
        22330                       => 'Bell Molluscs',
            22331                       => 'Albens Bell Mollusc',
            22332                       => 'Lindigoticum Bell Mollusc',
            22333                       => 'Carpasinus Bell Mollusc',
            22334                       => 'Blatteum Bell Mollusc',
            22335                       => 'Luteolum Bell Mollusc',
        22350                       => 'Umbrella Molluscs',
            22351                       => 'Luteolum Umbrella Mollusc',
            22352                       => 'Lindigoticum Umbrella Mollusc',
            22353                       => 'Viride Umbrella Mollusc',
        22370                       => 'Capsule Molluscs',
            22371                       => 'Luteolum Capsule Mollusc',
            22372                       => 'Lindigoticum Capsule Mollusc',
        22390                       => 'Reel Molluscs',
            22391                       => 'Luteolum Reel Mollusc',
            22392                       => 'Lindigoticum Reel Mollusc',
            22393                       => 'Viride Reel Mollusc',
        22410                       => 'Octahedral Pods',
            22411                       => 'Niveus Octahedral Pod',
            22412                       => 'Caeruleum Octahedral Pod',
            22413                       => 'Viride Octahedral Pod',
            22415                       => 'Rubeum Octahedral Pod',
        22430                       => 'Void Hearts',
            22431                       => 'Chryseum Void Heart',
        22450                       => 'Parasol Molluscs',
            22451                       => 'Luteolum Parasol Mollusc',
            22452                       => 'Lindigoticum Parasol Mollusc',
            22453                       => 'Viride Parasol Mollusc',
        22470                       => 'Bulb Molluscs',
            22471                       => 'Luteolum Bulb Mollusc',
            22472                       => 'Lindigoticum Bulb Mollusc',
            22473                       => 'Viride Bulb Mollusc',
        22490                       => 'Gyre Trees', // Flagged as Stolon Pods in game...
            22491                       => 'Viridis Gyre Tree',
            22492                       => 'Aurarius Gyre Tree',
        22510                       => 'Rhizome Pods',
            22511                       => 'Candidum Rhizome Pod',
            22512                       => 'Cobalteum Rhizome Pod',
            22513                       => 'Gypseeum Rhizome Pod',
            22514                       => 'Purpureum Rhizome Pod',
            22515                       => 'Rubeum Rhizome Pod',
        22530                       => 'Quadripartite Pods',
            22531                       => 'Albidum Quadripartite Pod',
            22532                       => 'Caeruleum Quadripartite Pod',
            22533                       => 'Viride Quadripartite Pod',
            22534                       => 'Blatteum Quadripartite Pod',
        22550                       => 'Bullet Molluscs',
            22551                       => 'Cereum Bullet Mollusc',
            22552                       => 'Lividum Bullet Mollusc',
            22553                       => 'Viride Bullet Mollusc',
            22554                       => 'Rubeum Bullet Mollusc',
            22555                       => 'Flavum Bullet Mollusc',
        22570                       => 'Calcite Plates',
            22571                       => 'Luteolum Calcite Plates',
            22572                       => 'Lindigoticum Calcite Plates',
            22573                       => 'Viride Calcite Plates',
        22590                       => 'Gyre Pods',
            22592                       => 'Aurarium Gyre Pod',
        22610                       => 'Squid Molluscs',
            22611                       => 'Albulum Squid Mollusc',
            22612                       => 'Caeruleum Squid Mollusc',
            22613                       => 'Puniceum Squid Mollusc',
            22614                       => 'Rubeum Squid Mollusc',
            22615                       => 'Roseum Squid Mollusc',
        22630                       => 'Chalice Pods',
            22631                       => 'Albidum Chalice Pod',
            22634                       => 'Ostrinum Chalice Pod',
        22651                       => 'Stolon Tree',
        22671                       => 'Stolon Pod',
        22690                       => 'Aster Pods',
            22691                       => 'Cereum Aster Pod',
            22692                       => 'Lindigoticum Aster Pod',
            22693                       => 'Prasinum Aster Pod',
            22694                       => 'Puniceum Aster Pod',
            22695                       => 'Rubellum Aster Pod',
        22710                       => 'Aster Trees',
            22711                       => 'Cereum Aster Tree',
            22713                       => 'Prasinum Aster Tree',
            22715                       => 'Rubellum Aster Tree',
        22730                       => 'Torus Molluscs',
            22732                       => 'Caeruleum Torus Mollusc',
            22735                       => 'Rubellum Torus Mollusc',
        22750                       => 'Fonticulua Campestris',
            22751                       => 'Fonticulua Campestris - Amethyst',
            22752                       => 'Fonticulua Campestris - Emerald',
            22753                       => 'Fonticulua Campestris - Mauve',
            22754                       => 'Fonticulua Campestris - Teal',
            22755                       => 'Fonticulua Campestris - Orange',
            22756                       => 'Fonticulua Campestris - Ocher',
            22757                       => 'Fonticulua Campestris - Green',
            22758                       => 'Fonticulua Campestris - Yellow',
            22759                       => 'Fonticulua Campestris - Red',
            22760                       => 'Fonticulua Campestris - Sage',
        22770                       => 'Osseus Spiralis',
            22772                       => 'Osseus Spiralis - Indigo',
            22774                       => 'Osseus Spiralis - Grey',
            22775                       => 'Osseus Spiralis - Emerald',
            22777                       => 'Osseus Spiralis - Lime',
            22778                       => 'Osseus Spiralis - Turquoise',
        22790                       => 'Osseus Fractus',
            22792                       => 'Osseus Fractus - Indigo',
            22794                       => 'Osseus Fractus - Grey',
            22797                       => 'Osseus Fractus - Lime',
            22798                       => 'Osseus Fractus - Turquoise',
        22810                       => 'Stratum Tectonicas',
            22811                       => 'Stratum Tectonicas - Green',
            22812                       => 'Stratum Tectonicas - Lime',
            22815                       => 'Stratum Tectonicas - Grey',
            22818                       => 'Stratum Tectonicas - Emerald',
            22819                       => 'Stratum Tectonicas - Amethyst',
        22830                       => 'Tussock Cultro',
            22831                       => 'Tussock Cultro - Emerald',
            22832                       => 'Tussock Cultro - Green',
            22833                       => 'Tussock Cultro - Sage',
            22834                       => 'Tussock Cultro - Lime',
            22835                       => 'Tussock Cultro - Teal',
            22838                       => 'Tussock Cultro - Yellow',
        22851                       => 'Stratum Paleas',
            22851                       => 'Stratum Paleas - Green',
            22852                       => 'Stratum Paleas - Lime',
            22855                       => 'Stratum Paleas - Grey',
            22858                       => 'Stratum Paleas - Emerald',
        22870                       => 'Frutexa Acus',
            22871                       => 'Frutexa Acus - Grey',
            22874                       => 'Frutexa Acus - Emerald',
            22878                       => 'Frutexa Acus - Green',
        
        22890                       => 'Bacterium Aurasus',
            22891                       => 'Bacterium Aurasus - Teal',
            22892                       => 'Bacterium Aurasus - Green',
            22893                       => 'Bacterium Aurasus - Sage',
            22894                       => 'Bacterium Aurasus - Emerald',
            22895                       => 'Bacterium Aurasus - Red',
            22897                       => 'Bacterium Aurasus - Yellow',
            22898                       => 'Bacterium Aurasus - Lime',
            22899                       => 'Bacterium Aurasus - Maroon',
            22900                       => 'Bacterium Aurasus - Indigo',
            22901                       => 'Bacterium Aurasus - Grey',
            22902                       => 'Bacterium Aurasus - Ocher',
        22910                       => 'Bacterium Nebulus',
            22911                       => 'Bacterium Nebulus - Green',
            22912                       => 'Bacterium Nebulus - Cobalt',
            22913                       => 'Bacterium Nebulus - Cyan',
            22914                       => 'Bacterium Nebulus - Gold',
            22915                       => 'Bacterium Nebulus - Orange',
        22930                       => 'Bacterium Scopulum',
            22931                       => 'Bacterium Scopulum - Red',
            22932                       => 'Bacterium Scopulum - Lime',
            22933                       => 'Bacterium Scopulum - White',
            22934                       => 'Bacterium Scopulum - Mulberry',
            22935                       => 'Bacterium Scopulum - Aquamarine',
            22936                       => 'Bacterium Scopulum - Peach',
        22950                       => 'Bacterium Acies',
            22951                       => 'Bacterium Acies - Aquamarine',
            22952                       => 'Bacterium Acies - Cobalt',
            22953                       => 'Bacterium Acies - White',
            22954                       => 'Bacterium Acies - Cyan',
            22955                       => 'Bacterium Acies - Lime',
            22956                       => 'Bacteria Acies - Magenta',
        22970                       => 'Bacterium Vesicula',
            22971                       => 'Bacterium Vesicula - Red',
            22972                       => 'Bacterium Vesicula - Lime',
            22973                       => 'Bacterium Vesicula - Mulberry',
            22974                       => 'Bacterium Vesicula - Cyan',
            22975                       => 'Bacterium Vesicula - Gold',
            22976                       => 'Bacteria Vesicula - Orange',
        22990                       => 'Bacterium Alcyoneum',
            22991                       => 'Bacterium Alcyoneum - Teal',
            22992                       => 'Bacterium Alcyoneum - Green',
            22993                       => 'Bacterium Alcyoneum - Sage',
            22994                       => 'Bacterium Alcyoneum - Emerald',
            22995                       => 'Bacterium Alcyoneum - Red',
            22997                       => 'Bacterium Alcyoneum - Yellow',
            22998                       => 'Bacterium Alcyoneum - Lime',
            22999                       => 'Bacterium Alcyoneum - Maroon',
            23000                       => 'Bacterium Alcyoneum - Indigo',
            23002                       => 'Bacterium Alcyoneum - Ocher',
        23010                       => 'Bacterium Tela',
            23011                       => 'Bacterium Tela - Yellow',
            23012                       => 'Bacterium Tela - Magenta',
            23013                       => 'Bacterium Tela - Gold',
            23014                       => 'Bacterium Tela - Green',
            23015                       => 'Bacterium Tela - Cobalt',
            23016                       => 'Bacteria Tela - Orange',
        23030                       => 'Bacterium Informem',
            23031                       => 'Bacterium Informem - Cobalt',
            23032                       => 'Bacterium Informem - Gold',
            23033                       => 'Bacterium Informem - Yellow',
            23034                       => 'Bacterium Informem - Red',
            23035                       => 'Bacterium Informem - Aquamarine',
            23036                       => 'Bacteria Informem - Lime',
        23050                       => 'Bacterium Volu',
            23051                       => 'Bacterium Volu - Cyan',
            23052                       => 'Bacterium Volu - Gold',
            23053                       => 'Bacterium Volu - Red',
            23054                       => 'Bacterium Volu - Lime',
            23055                       => 'Bacterium Volu - Cobalt',
            23056                       => 'Bacterium Volu - Aquamarine',
        23070                       => 'Bacterium Bullaris',
            23071                       => 'Bacterium Bullaris - Lime',
            23072                       => 'Bacterium Bullaris - Aquamarine',
            23073                       => 'Bacterium Bullaris - Cobalt',
            23074                       => 'Bacterium Bullaris - Red',
            23075                       => 'Bacterium Bullaris - Gold',
            23076                       => 'Bacterium Bullaris - Yellow',
        23090                       => 'Bacterium Omentum',
            23091                       => 'Bacterium Omentum - Blue',
            23092                       => 'Bacterium Omentum - Lime',
            23093                       => 'Bacterium Omentum - Peach',
            23094                       => 'Bacterium Omentum - White',
            23095                       => 'Bacterium Omentum - Aquamarine',
            23096                       => 'Bacterium Omentum - Red',
        23110                       => 'Bacterium Aurasus',
            23111                       => 'Bacterium Cerbrus - Teal',
            23112                       => 'Bacterium Cerbrus - Green',
            23113                       => 'Bacterium Cerbrus - Sage',
            23114                       => 'Bacterium Cerbrus - Emerald',
            23115                       => 'Bacterium Cerbrus - Red',
            23117                       => 'Bacterium Cerbrus - Yellow',
            23118                       => 'Bacterium Cerbrus - Lime',
            23119                       => 'Bacterium Cerbrus - Maroon',
            23120                       => 'Bacterium Cerbrus - Indigo',
            23121                       => 'Bacterium Cerbrus - Grey',
            23122                       => 'Bacterium Cerbrus - Turquoise',
        23130                       => 'Bacterium Verrata',
            23131                       => 'Bacterium Verrata - Peach',
            23132                       => 'Bacterium Verrata - Red',
            23133                       => 'Bacterium Verrata - Blue',
            23134                       => 'Bacterium Verrata - White',
            23135                       => 'Bacterium Verrata - Lime',
            23136                       => 'Bacterium Verrata - Mulberry',



        31010                       => 'Thargoid Interceptor',
            31011                       => 'Thargoid Interceptor Cyclops',
            31012                       => 'Thargoid Interceptor Basilisk',
            31013                       => 'Thargoid Interceptor Medusa',
            31014                       => 'Thargoid Interceptor Hydra',
            31015                       => 'Thargoid Interceptor Shipwreck',
        31021                       => 'Thargoid Scavengers',
        31030                       => 'Thargoid Scouts',
            31031                       => 'Thargoid Scout Marauder',
            31032                       => 'Thargoid Scout Berserker',
            31033                       => 'Thargoid Scout Inciter',
            31034                       => 'Thargoid Scout Regenerator',
            31035                       => 'Thargoid Scout Shipwreck',
        31041                       => 'Thargoid Uplink Device',
        31051                       => 'Thargoid Pod',
        31061                       => 'Thargoid Device',



        32011                       => 'Guardian Codex',
        32021                       => 'Guardian Data Terminal',
        32031                       => 'Guardian Pylon',
        32041                       => 'Guardian Relic Tower',
        32051                       => 'Guardian Sentinel',
        32061                       => 'Guardian Beacon',
    ];

    /**
     * List of aliases received from Frontier
     *
     * Every aliases are sanitized before matching
     *     => trim
     *     => strtolower
     */
    static protected $alias = [
        'codex_ent_o_type'                                  => 11011,
        'codex_ent_o_typegiant'                             => 11012,
        'codex_ent_o_typesupergiant'                        => 11013,

        'codex_ent_b_type'                                  => 11021,
        'codex_ent_b_typegiant'                             => 11022,
        'codex_ent_b_typesupergiant'                        => 11023,

        'codex_ent_a_type'                                  => 11031,
        'codex_ent_a_typegiant'                             => 11032,
        'codex_ent_a_typesupergiant'                        => 11033,

        'codex_ent_f_type'                                  => 11041,
        'codex_ent_f_typegiant'                             => 11042,
        'codex_ent_f_typesupergiant'                        => 11043,

        'codex_ent_g_type'                                  => 11051,
        'codex_ent_g_typegiant'                             => 11052,
        'codex_ent_g_typesupergiant'                        => 11053,

        'codex_ent_k_type'                                  => 11061,
        'codex_ent_k_typegiant'                             => 11062,
        'codex_ent_k_typesupergiant'                        => 11063,

        'codex_ent_m_type'                                  => 11071,
        'codex_ent_m_typegiant'                             => 11072,
        'codex_ent_m_typesupergiant'                        => 11073,

        'codex_ent_a_type'                                  => 11031,

        'codex_ent_f_type'                                  => 11041,

        'codex_ent_g_type'                                  => 11051,

        'codex_ent_k_type'                                  => 11061,

        'codex_ent_m_type'                                  => 11071,

        'codex_ent_l_type'                                  => 11081,

        'codex_ent_t_type'                                  => 11091,

        'codex_ent_tts_type'                                => 11101,

        'codex_ent_aebe_type'                               => 11111,

        'codex_ent_y_type'                                  => 11121,

        'codex_ent_c_type'                                  => 11131,
        'codex_ent_c_typegiant'                             => 11132,
        'codex_ent_c_typesupergiant'                        => 11133,
        'codex_ent_c_typehypergiant'                        => 11134,

        'codex_ent_cn_typegiant'                            => 11142,

        'codex_ent_cj_typegiant'                            => 11152,

        'codex_ent_ms_typegiant'                            => 11162,

        'codex_ent_s_type'                                  => 11171,
        'codex_ent_s_typegiant'                             => 11172,

        'codex_ent_w_type'                                  => 11181,
        'codex_ent_wc_type'                                 => 11183,
        'codex_ent_wn_type'                                 => 11184,
        'codex_ent_wnc_type'                                => 11185,
        'codex_ent_wo_type'                                 => 11186,

        'codex_ent_d_type'                                  => 11191,
        'codex_ent_da_type'                                 => 11192,
        'codex_ent_dab_type'                                => 11194,
        'codex_ent_dav_type'                                => 11196,
        'codex_ent_daz_type'                                => 11197,
        'codex_ent_db_type'                                 => 11198,
        'codex_ent_dbv_type'                                => 11199,
        'codex_ent_dbz_type'                                => 11200,
        'codex_ent_do_type'                                 => 11204,
        'codex_ent_dov_type'                                => 11205,
        'codex_ent_dq_type'                                 => 11206,
        'codex_ent_dc_type'                                 => 11207,
        'codex_ent_dcv_type'                                => 11208,

        'codex_ent_neutron_stars'                           => 11221,

        'codex_ent_black_holes'                             => 11231,

        'codex_ent_supermassiveblack_holes'                 => 11241,



        'codex_ent_standard_water_giant'                    => 12011,
        'codex_ent_green_water_giant'                       => 12012,

        'codex_ent_standard_giant_with_water_life'          => 12031,
        'codex_ent_green_giant_with_water_life'             => 12032,

        'codex_ent_standard_giant_with_ammonia_life'        => 12051,

        'codex_ent_standard_sudarsky_class_i'               => 12071,
        'codex_ent_green_sudarsky_class_i'                  => 12072,

        'codex_ent_standard_sudarsky_class_ii'              => 12091,
        'codex_ent_green_sudarsky_class_ii'                 => 12092,

        'codex_ent_standard_sudarsky_class_iii'             => 12111,
        'codex_ent_green_sudarsky_class_iii'                => 12112,

        'codex_ent_standard_sudarsky_class_iv'              => 12131,

        'codex_ent_standard_sudarsky_class_v'               => 12151,

        'codex_ent_standard_helium'                         => 12171,
        'codex_ent_standard_helium_rich'                    => 12191,



        'codex_ent_earth_likes'                             => 13011,

        'codex_ent_standard_ammonia_worlds'                 => 13021,
        'codex_ent_trf_ammonia_worlds'                      => 13022,

        'codex_ent_standard_water_worlds'                   => 13031,
        'codex_ent_trf_water_worlds'                        => 13032,

        'codex_ent_standard_metal_rich_no_atmos'            => 13041,
        'codex_ent_trf_metal_rich_no_atmos'                 => 13042,

        'codex_ent_standard_high_metal_content_no_atmos'    => 13051,
        'codex_ent_trf_high_metal_content_no_atmos'         => 13052,

        'codex_ent_standard_rocky_no_atmos'                 => 13061,
        'codex_ent_trf_rocky_no_atmos'                      => 13062,

        'codex_ent_standard_rocky_ice_no_atmos'             => 13071,

        'codex_ent_standard_ice_no_atmos'                   => 13081,

        'codex_ent_standard_ter_metal_rich'                 => 13091,
        'codex_ent_trf_ter_metal_rich'                      => 13092,

        'codex_ent_standard_ter_high_metal_content'         => 13101,
        'codex_ent_trf_ter_high_metal_content'              => 13102,

        'codex_ent_standard_ter_rocky'                      => 13111,
        'codex_ent_trf_ter_rocky'                           => 13112,

        'codex_ent_standard_ter_rocky_ice'                  => 13121,

        'codex_ent_standard_ter_ice'                        => 13131,



        'codex_ent_fumarole_sulphurdioxidemagma'            => 21011,
        'codex_ent_fumarole_watergeysers'                   => 21012,
        'codex_ent_fumarole_silicatevapourgeysers'          => 21013,
        'codex_ent_fumarole_carbondioxidegeysers'           => 21014,

        'codex_ent_icefumarole_sulphurdioxidemagma'         => 21031,
        'codex_ent_icefumarole_watergeysers'                => 21032,
        'codex_ent_icefumarole_carbondioxidegeysers'        => 21033,
        'codex_ent_icefumarole_ammoniageysers'              => 21034,
        'codex_ent_icefumarole_methanegeysers'              => 21035,
        'codex_ent_icefumarole_nitrogengeysers'             => 21036,
        'codex_ent_icefumarole_silicatevapourgeysers'       => 21037,

        'codex_ent_geysers_watergeysers'                    => 21051,

        'codex_ent_icegeysers_watergeysers'                 => 21071,
        'codex_ent_icegeysers_carbondioxidegeysers'         => 21072,
        'codex_ent_icegeysers_ammoniageysers'               => 21073,
        'codex_ent_icegeysers_methanegeysers'               => 21074,
        'codex_ent_icegeysers_nitrogengeysers'              => 21075,

        'codex_ent_lava_spouts_silicatemagma'               => 21091,
        'codex_ent_lava_spouts_ironmagma'                   => 21092,

        'codex_ent_gas_vents_sulphurdioxidemagma'           => 21111,
        'codex_ent_gas_vents_watergeysers'                  => 21112,
        'codex_ent_gas_vents_carbondioxidegeysers'          => 21113,
        'codex_ent_gas_vents_silicatevapourgeysers'         => 21114,

        'codex_ent_gas_clds_blue'                           => 21131,
        'codex_ent_gas_clds_green'                          => 21132,
        'codex_ent_gas_clds_orange'                         => 21133,
        'codex_ent_gas_clds_pink'                           => 21134,
        'codex_ent_gas_clds_red'                            => 21135,
        'codex_ent_gas_clds_yellow'                         => 21136,
        'codex_ent_gas_clds_light'                          => 21137,
        'codex_ent_gas_clds_green_storm'                    => 21139,
        'codex_ent_gas_clds_orange_storm'                   => 21140,
        'codex_ent_gas_clds_pink_storm'                     => 21141,
        'codex_ent_gas_clds_red_storm'                      => 21142,
        'codex_ent_gas_clds_yellow_storm'                   => 21143,

        'codex_ent_l_phn_part_eng_002'                      => 21151,
        'codex_ent_l_phn_part_eng_003'                      => 21152,
        'codex_ent_l_phn_part_eng_004'                      => 21153,
        'codex_ent_l_phn_part_eng_005'                      => 21154,
        'codex_ent_l_phn_part_eng_006'                      => 21155,
        'codex_ent_l_phn_part_eng_008'                      => 21157,
        'codex_ent_l_phn_part_eng_010'                      => 21159,
        'codex_ent_l_phn_part_eng_012'                      => 21161,
        'codex_ent_l_phn_part_eng_013'                      => 21162,
        'codex_ent_l_phn_part_eng_014'                      => 21163,
        'codex_ent_l_phn_part_eng_015'                      => 21164,
        'codex_ent_l_phn_part_eng_016'                      => 21165,

        'codex_ent_l_phn_part_orb_001'                      => 21171,
        'codex_ent_l_phn_part_orb_002'                      => 21172,
        'codex_ent_l_phn_part_orb_004'                      => 21174,
        'codex_ent_l_phn_part_orb_006'                      => 21176,
        'codex_ent_l_phn_part_orb_008'                      => 21178,
        'codex_ent_l_phn_part_orb_009'                      => 21179,

        'codex_ent_l_phn_part_clus_003'                     => 21191,
        'codex_ent_l_phn_part_clus_008'                     => 21194,
        'codex_ent_l_phn_part_clus_009'                     => 21195,
        'codex_ent_l_phn_part_clus_010'                     => 21196,
        'codex_ent_l_phn_part_clus_013'                     => 21199,

        'codex_ent_l_phn_part_cld_001'                      => 21211,
        'codex_ent_l_phn_part_cld_002'                      => 21212,
        'codex_ent_l_phn_part_cld_003'                      => 21213,
        'codex_ent_l_phn_part_cld_004'                      => 21214,
        'codex_ent_l_phn_part_cld_005'                      => 21215,
        'codex_ent_l_phn_part_cld_006'                      => 21216,
        'codex_ent_l_phn_part_cld_008'                      => 21217,
        'codex_ent_l_phn_part_cld_009'                      => 21218,
        'codex_ent_l_phn_part_cld_011'                      => 21220,
        'codex_ent_l_phn_part_cld_016'                      => 21222,
        'codex_ent_l_phn_part_cld_017'                      => 21223,

        'codex_ent_l_phn_part_clus_001'                     => 21231,
        'codex_ent_l_phn_part_clus_002'                     => 21232,
        'codex_ent_l_phn_part_clus_005'                     => 21234,

        'codex_ent_l_phn_part_cld_014'                      => 21252,
        'codex_ent_l_phn_part_cld_007'                      => 21254,



        'codex_ent_spoi_ball'                               => 22011,

        'codex_ent_spoi_ball_lattice'                       => 22031,

        'codex_ent_thargoid_barnacle_01'                    => 22051,
        'codex_ent_thargoid_barnacle_02'                    => 22052,
        'codex_ent_thargoid_barnacle_spikes'                => 22053,

        'codex_ent_seed'                                    => 22071,
        'codex_ent_seedabcd_01'                             => 22072,
        'codex_ent_seedabcd_02'                             => 22073,
        'codex_ent_seedabcd_03'                             => 22074,
        'codex_ent_seedefgh'                                => 22075,
        'codex_ent_seedefgh_01'                             => 22076,
        'codex_ent_seedefgh_03'                             => 22077,
        'codex_ent_seedefgh_02'                             => 22078,

        'codex_ent_cone'                                    => 22091,

        'codex_ent_sphere'                                  => 22111,
        'codex_ent_sphereabcd_01'                           => 22112,
        'codex_ent_sphereabcd_02'                           => 22113,
        'codex_ent_sphereabcd_03'                           => 22114,
        'codex_ent_sphereefgh'                              => 22115,
        'codex_ent_sphereefgh_01'                           => 22116,
        'codex_ent_sphereefgh_02'                           => 22117,
        'codex_ent_sphereefgh_03'                           => 22118,

        'codex_ent_tube'                                    => 22131,
        'codex_ent_tubeabcd_01'                             => 22132,
        'codex_ent_tubeabcd_02'                             => 22133,
        'codex_ent_tubeabcd_03'                             => 22134,
        'codex_ent_tubeefgh'                                => 22135,
        'codex_ent_tubeefgh_01'                             => 22136,
        'codex_ent_tubeefgh_02'                             => 22137,
        'codex_ent_tubeefgh_03'                             => 22138,

        'codex_ent_l_cry_metcry_gr'                         => 22151,
        'codex_ent_l_cry_metcry_pur'                        => 22152,
        'codex_ent_l_cry_metcry_red'                        => 22153,
        'codex_ent_l_cry_metcry_yw'                         => 22154,

        'codex_ent_s_seed_sdtp04_def'                       => 22171,
        'codex_ent_s_seed_sdtp04_bl'                        => 22172,
        'codex_ent_s_seed_sdtp04_pur'                       => 22173,
        'codex_ent_s_seed_sdtp04_red'                       => 22174,

        'codex_ent_small_org_moll01_v1_def'                 => 22191,
        'codex_ent_small_org_moll01_v1_bl'                  => 22192,
        'codex_ent_small_org_moll01_v1_gr'                  => 22193,
        'codex_ent_small_org_moll01_v1_pnk'                 => 22194,
        'codex_ent_small_org_moll01_v1_pur'                 => 22195,
        'codex_ent_small_org_moll01_v1_red'                 => 22196,
        'codex_ent_small_org_moll01_v1_y'                   => 22197,

        'codex_ent_l_cry_iccry_bl'                          => 22211,
        'codex_ent_l_cry_iccry_gr'                          => 22212,
        'codex_ent_l_cry_iccry_pk'                          => 22213,
        'codex_ent_l_cry_iccry_pur'                         => 22214,
        'codex_ent_l_cry_iccry_red'                         => 22215,
        'codex_ent_l_cry_iccry_wte'                         => 22216,
        'codex_ent_l_cry_iccry_yw'                          => 22217,

        'codex_ent_l_cry_qtzcry_bl'                         => 22231,
        'codex_ent_l_cry_qtzcry_gr'                         => 22232,
        'codex_ent_l_cry_qtzcry_pur'                        => 22233,
        'codex_ent_l_cry_qtzcry_wte'                        => 22234,
        'codex_ent_l_cry_qtzcry_yw'                         => 22235,
        'codex_ent_l_cry_qtzcry_red'                        => 22236,
        'codex_ent_l_cry_qtzcry_pk'                         => 22237,

        'codex_ent_ground_struct_ice'                       => 22251,

        'codex_ent_s_seed_sdtp01_def'                       => 22271,
        'codex_ent_s_seed_sdtp01_bl'                        => 22272,
        'codex_ent_s_seed_sdtp01_gr'                        => 22273,
        'codex_ent_s_seed_sdtp01_pur'                       => 22274,
        'codex_ent_s_seed_sdtp01_red'                       => 22275,

        'codex_ent_l_seed_pln01_v1_def'                     => 22291,
        'codex_ent_l_seed_pln01_v1_bl'                      => 22292,
        'codex_ent_l_seed_pln01_v1_gr'                      => 22293,
        'codex_ent_l_seed_pln01_v1_pur'                     => 22294,
        'codex_ent_l_seed_pln01_v1_red'                     => 22295,

        'codex_ent_vents'                                   => 22311,

        'codex_ent_small_org_moll01_v6_def'                 => 22331,
        'codex_ent_small_org_moll01_v6_bl'                  => 22332,
        'codex_ent_small_org_moll01_v6_gr'                  => 22333,
        'codex_ent_small_org_moll01_v6_pur'                 => 22334,
        'codex_ent_small_org_moll01_v6_y'                   => 22335,

        'codex_ent_l_org_moll03_v3_def'                     => 22351,
        'codex_ent_l_org_moll03_v3_dark'                    => 22352,
        'codex_ent_l_org_moll03_v3_earth'                   => 22353,

        'codex_ent_l_org_moll03_v4_def'                     => 22371,
        'codex_ent_l_org_moll03_v4_dark'                    => 22372,

        'codex_ent_l_org_moll03_v6_def'                     => 22391,
        'codex_ent_l_org_moll03_v6_dark'                    => 22392,
        'codex_ent_l_org_moll03_v6_earth'                   => 22393,

        'codex_ent_s_seed_sdtp03_def'                       => 22411,
        'codex_ent_s_seed_sdtp03_bl'                        => 22412,
        'codex_ent_s_seed_sdtp03_gr'                        => 22413,
        'codex_ent_s_seed_sdtp03_red'                       => 22415,

        'codex_ent_spoi_seedweed01_v1'                      => 22431,

        'codex_ent_l_org_moll03_v1_def'                     => 22451,
        'codex_ent_l_org_moll03_v1_dark'                    => 22452,
        'codex_ent_l_org_moll03_v1_earth'                   => 22453,

        'codex_ent_l_org_moll03_v2_def'                     => 22471,
        'codex_ent_l_org_moll03_v2_dark'                    => 22472,
        'codex_ent_l_org_moll03_v2_earth'                   => 22473,

        'codex_ent_spoi_seedpolyp01_v1'                     => 22491,
        'codex_ent_spoi_seedpolyp01_v1_gld'                 => 22492,

        'codex_ent_s_seed_sdtp07_def'                       => 22511,
        'codex_ent_s_seed_sdtp07_bl'                        => 22512,
        'codex_ent_s_seed_sdtp07_gr'                        => 22513,
        'codex_ent_s_seed_sdtp07_pur'                       => 22514,
        'codex_ent_s_seed_sdtp07_red'                       => 22515,

        'codex_ent_s_seed_sdtp08_def'                       => 22531,
        'codex_ent_s_seed_sdtp08_bl'                        => 22532,
        'codex_ent_s_seed_sdtp08_gr'                        => 22533,
        'codex_ent_s_seed_sdtp08_pur'                       => 22534,

        'codex_ent_small_org_moll01_v4_def'                 => 22551,
        'codex_ent_small_org_moll01_v4_bl'                  => 22552,
        'codex_ent_small_org_moll01_v4_gr'                  => 22553,
        'codex_ent_small_org_moll01_v4_red'                 => 22554,
        'codex_ent_small_org_moll01_v4_y'                   => 22555,

        'codex_ent_l_org_pltfun_v1_def'                     => 22571,
        'codex_ent_l_org_pltfun_v1_bl'                      => 22572,
        'codex_ent_l_org_pltfun_v1_gr'                      => 22573,

        'codex_ent_s_seed_sdtp06_gd'                        => 22592,

        'codex_ent_small_org_moll01_v3_def'                 => 22611,
        'codex_ent_small_org_moll01_v3_bl'                  => 22612,
        'codex_ent_small_org_moll01_v3_pur'                 => 22613,
        'codex_ent_small_org_moll01_v3_red'                 => 22614,
        'codex_ent_small_org_moll01_v3_pnk'                 => 22615,

        'codex_ent_s_seed_sdtp05_def'                       => 22631,
        'codex_ent_s_seed_sdtp05_pur'                       => 22634,

        'codex_ent_l_seed_sdrt02_v3'                        => 22651,

        'codex_ent_spoi_root_seeds'                         => 22671,

        'codex_ent_s_seed_sdtp02_def'                       => 22691,
        'codex_ent_s_seed_sdtp02_bl'                        => 22692,
        'codex_ent_s_seed_sdtp02_gr'                        => 22693,
        'codex_ent_s_seed_sdtp02_pur'                       => 22694,
        'codex_ent_s_seed_sdtp02_red'                       => 22695,

        'codex_ent_l_seed_pln02_v3_def'                     => 22711,
        'codex_ent_l_seed_pln02_v3_gr'                      => 22713,
        'codex_ent_l_seed_pln02_v3_red'                     => 22715,

        'codex_ent_small_org_moll01_v2_bl'                  => 22732,
        'codex_ent_small_org_moll01_v2_red'                 => 22735,

        'codex_ent_fonticulus_02_m'                         => 22751,
        'codex_ent_fonticulus_02_k'                         => 22752,
        'codex_ent_fonticulus_02_l'                         => 22753,
        'codex_ent_fonticulus_02_g'                         => 22754,
        'codex_ent_fonticulus_02_t'                         => 22755,
        'codex_ent_fonticulus_02_y'                         => 22756,
        'codex_ent_fonticulus_02_a'                         => 22757,
        'codex_ent_fonticulus_02_f'                         => 22758,
        'codex_ent_fonticulus_02_tts'                       => 22759,
        'codex_ent_fonticulus_02_n'                         => 22760,

        'codex_ent_osseus_03_k'                             => 22772,
        'codex_ent_osseus_03_g'                             => 22774,
        'codex_ent_osseus_03_t'                             => 22775,
        'codex_ent_osseus_03_a'                             => 22777,
        'codex_ent_osseus_03_f'                             => 22778,

        'codex_ent_osseus_01_k'                             => 22792,
        'codex_ent_osseus_01_g'                             => 22794,
        'codex_ent_osseus_01_a'                             => 22797,
        'codex_ent_osseus_01_f'                             => 22798,

        'codex_ent_stratum_07_m'                            => 22811,
        'codex_ent_stratum_07_k'                            => 22812,
        'codex_ent_stratum_07_t'                            => 22815,
        'codex_ent_stratum_07_f'                            => 22818,
        'codex_ent_stratum_07_tts'                          => 22819,

        'codex_ent_tussocks_04_m'                           => 22831,
        'codex_ent_tussocks_04_k'                           => 22832,
        'codex_ent_tussocks_04_l'                           => 22833,
        'codex_ent_tussocks_04_g'                           => 22834,
        'codex_ent_tussocks_04_t'                           => 22835,
        'codex_ent_tussocks_04_f'                           => 22838,

        'codex_ent_stratum_02_m'                            => 22851,
        'codex_ent_stratum_02_k'                            => 22852,
        'codex_ent_stratum_02_t'                            => 22855,
        'codex_ent_stratum_02_f'                            => 22858,

        'codex_ent_shrubs_02_m'                             => 22871,
        'codex_ent_shrubs_02_g'                             => 22874,
        'codex_ent_shrubs_02_f'                             => 22878,

        'codex_ent_bacterial_01_m'                          => 22891,
        'codex_ent_bacterial_01_k'                          => 22892,
        'codex_ent_bacterial_01_l'                          => 22893,
        'codex_ent_bacterial_01_g'                          => 22894,
        'codex_ent_bacterial_01_t'                          => 22895,
        'codex_ent_bacterial_01_a'                          => 22897,
        'codex_ent_bacterial_01_f'                          => 22898,
        'codex_ent_bacterial_01_tts'                        => 22899,
        'codex_ent_bacterial_01_n'                          => 22900,
        'codex_ent_bacterial_01_b'                          => 22901,
        'codex_ent_bacterial_01_d'                          => 22902,
        
        'codex_ent_bacterial_02_tellurium'                  => 22911,
        'codex_ent_bacterial_02_yttrium'                    => 22912,
        'codex_ent_bacterial_02_technetium'                 => 22913,
        'codex_ent_bacterial_02_polonium'                   => 22914,
        'codex_ent_bacterial_02_ruthenium'                  => 22915,
        
        'codex_ent_bacterial_03_niobium'                    => 22931,
        'codex_ent_bacterial_03_molybdenum'                 => 22932,
        'codex_ent_bacterial_03_cadmium'                    => 22933,
        'codex_ent_bacterial_03_tin'                        => 22934,
        'codex_ent_bacterial_03_tungsten'                   => 22935,
        'codex_ent_bacterial_03_mercury'                    => 22936,
        
        'codex_ent_bacterial_04_yttrium'                    => 22951,
        'codex_ent_bacterial_04_ruthenium'                  => 22952,
        'codex_ent_bacterial_04_tellurium'                  => 22953,
        'codex_ent_bacterial_04_antimony'                   => 22954,
        'codex_ent_bacterial_04_technetium'                 => 22955,
        'codex_ent_bacterial_04_polonium'                   => 22956,
        
        'codex_ent_bacterial_05_tellurium'                  => 22971,
        'codex_ent_bacterial_05_yttrium'                    => 22972,
        'codex_ent_bacterial_05_ruthenium'                  => 22973,
        'codex_ent_bacterial_05_antimony'                   => 22974,
        'codex_ent_bacterial_05_technetium'                 => 22975,
        'codex_ent_bacterial_05_polonium'                   => 22976,

        'codex_ent_bacterial_06_m'                          => 22991,
        'codex_ent_bacterial_06_k'                          => 22992,
        'codex_ent_bacterial_06_l'                          => 22993,
        'codex_ent_bacterial_06_g'                          => 22994,
        'codex_ent_bacterial_06_t'                          => 22995,
        'codex_ent_bacterial_06_a'                          => 22997,
        'codex_ent_bacterial_06_f'                          => 22998,
        'codex_ent_bacterial_06_tts'                        => 22999,
        'codex_ent_bacterial_06_n'                          => 23000,
        'codex_ent_bacterial_06_d'                          => 23002,
        
        'codex_ent_bacterial_07_molybdenum'                 => 23011,
        'codex_ent_bacterial_07_niobium'                    => 23012,
        'codex_ent_bacterial_07_cadmium'                    => 23013,
        'codex_ent_bacterial_07_tungsten'                   => 23014,
        'codex_ent_bacterial_07_tin'                        => 23015,
        'codex_ent_bacterial_07_mercury'                    => 23016,
        
        'codex_ent_bacterial_08_yttrium'                    => 23031,
        'codex_ent_bacterial_08_ruthenium'                  => 23032,
        'codex_ent_bacterial_08_tellurium'                  => 23033,
        'codex_ent_bacterial_08_antimony'                   => 23034,
        'codex_ent_bacterial_08_technetium'                 => 23035,
        'codex_ent_bacterial_08_polonium'                   => 23036,
        
        'codex_ent_bacterial_09_tellurium'                  => 23051,
        'codex_ent_bacterial_09_yttrium'                    => 23052,
        'codex_ent_bacterial_09_antimony'                   => 23053,
        'codex_ent_bacterial_09_technetium'                 => 23054,
        'codex_ent_bacterial_09_ruthenium'                  => 23055,
        'codex_ent_bacterial_09_polonium'                   => 23056,
        
        'codex_ent_bacterial_10_tellurium'                  => 23071,
        'codex_ent_bacterial_10_ruthenium'                  => 23072,
        'codex_ent_bacterial_10_antimony'                   => 23073,
        'codex_ent_bacterial_10_yttrium'                    => 23074,
        'codex_ent_bacterial_10_technetium'                 => 23075,
        'codex_ent_bacterial_10_polonium'                   => 23076,
        
        'codex_ent_bacterial_11_tungsten'                   => 23091,
        'codex_ent_bacterial_11_cadmium'                    => 23092,
        'codex_ent_bacterial_11_niobium'                    => 23093,
        'codex_ent_bacterial_11_mercury'                    => 23094,
        'codex_ent_bacterial_11_molybdenum'                 => 23095,
        'codex_ent_bacterial_11_tin'                        => 23096,

        'codex_ent_bacterial_12_m'                          => 23111,
        'codex_ent_bacterial_12_k'                          => 23112,
        'codex_ent_bacterial_12_l'                          => 23113,
        'codex_ent_bacterial_12_g'                          => 23114,
        'codex_ent_bacterial_12_t'                          => 23115,
        'codex_ent_bacterial_12_a'                          => 23117,
        'codex_ent_bacterial_12_f'                          => 23118,
        'codex_ent_bacterial_12_tts'                        => 23119,
        'codex_ent_bacterial_12_n'                          => 23120,
        'codex_ent_bacterial_12_b'                          => 23121,
        'codex_ent_bacterial_12_o'                          => 23122,
        
        'codex_ent_bacterial_13_cadmium'                    => 23131,
        'codex_ent_bacterial_13_mercury'                    => 23132,
        'codex_ent_bacterial_13_tin'                        => 23133,
        'codex_ent_bacterial_13_molybdenum'                 => 23134,
        'codex_ent_bacterial_13_tungsten'                   => 23135,
        'codex_ent_bacterial_13_niobium'                    => 23136,



        'codex_ent_cyclops'                                 => 31011,
        'codex_ent_basilisk'                                => 31012,
        'codex_ent_medusa'                                  => 31013,
        'codex_ent_hydra'                                   => 31014,
        'codex_ent_wrecked_interceptor'                     => 31015,

        'codex_ent_scavengers'                              => 31021,

        'codex_ent_marauder'                                => 31031,
        'codex_ent_berserker'                               => 31032,
        'codex_ent_inciter'                                 => 31033,
        'codex_ent_regenerator'                             => 31034,
        'codex_ent_wrecked_scout'                           => 31035,

        'codex_ent_tg_datascan'                             => 31041,

        'codex_ent_tg_pod'                                  => 31051,

        'codex_ent_tg_transmitter'                          => 31061,



        'codex_ent_guardian_data_logs'                      => 32011,
        'codex_ent_guardian_terminal'                       => 32021,
        'codex_ent_guardian_pylon'                          => 32031,
        'codex_ent_relic_tower'                             => 32041,
        'codex_ent_guardian_sentinel'                       => 32051,
        'codex_ent_guardian_beacons'                        => 32061,
    ];
}